[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzepplin/contracts=lib/openzepplin-contracts/contracts"]
ffi = true
fs_permissions = [{access = "read-write", path = "./img/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
